### ISSUE TITLE
Error on Python 3 related to "basestring"

### ISSUE THREAD

**Issue by danames** [hydroshare/hs_restclient#12]
Here's the error on Python 3 I just got:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/hs_restclient/__init__.py", line 572, in addResourceFile
    close_fd = self._prepareFileForUpload(params, resource_file)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/hs_restclient/__init__.py", line 180, in _prepareFileForUpload
    if isinstance(resource_file, basestring):
NameError: name 'basestring' is not defined

**Comment by mtpain** [comment]
Just ran into this myself. This appears to be a duplicate of #9
