### ISSUE TITLE
JSON object error

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hs_restclient#55]
I’m getting the following error every once in a while when downloading a resource using hs_restclient.getResource. My function runs inside a thread, but it looks like the error occurs inside the hs_restclient when loading json after the download completes. I’m hoping that you may have a chance to look at this.
threads.runThreadedFunction('Downloading Resource', 'Download Finished', self.hs.getResource,
                                            resourceid, destination=dst, unzip=True)

Exception in thread Thread-7:
 Traceback (most recent call last):
 File "/opt/conda/lib/python3.5/threading.py", line 914, in _bootstrap_inner 
      self.run()
 File "/opt/conda/lib/python3.5/threading.py", line 862, in run
      self._target(*self._args, **self._kwargs)
 File "/home/jovyan/work/notebooks/utilities/hydroshare/threads.py", line 23, in f
      res = self.func(*args, **kwargs)
 File "/opt/conda/lib/python3.5/site-packages/hs_restclient-1.2.6-py3.5.egg/hs_restclient/__init__.py",
      line 742, in getResource
        stream = self._getBagStream(pid, wait_for_bag_creation)
 File "/opt/conda/lib/python3.5/site-packages/hs_restclient-1.2.6-py3.5.egg/hs_restclient/__init__.py", 
      line 792, in _getBagStream
          content = json.loads(r.content)
 File "/opt/conda/lib/python3.5/json/__init__.py", line 312, in loads
      s.__class__.__name__))
 TypeError: the JSON object must be str, not 'bytes'

**Comment by gantian127** [comment]
@aphelionz Would you please let me know whether this has been fixed or not? I recently have the same issue when I use hs_restclient to download the resource bag. Thank you!

**Comment by aphelionz** [comment]
Commenting to unassign myself

**Comment by aphelionz** [comment]
Unassign me

**Comment by aphelionz** [comment]
would you mind un-assigning me

**Comment by aphelionz** [comment]
@Castronova please un-assign me from this ticket when you get a chance

**Comment by aphelionz** [comment]
@sblack-usu can you?
