### ISSUE TITLE
Add functionality to support specific file upload endpoint

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hs_restclient#57]

**Comment by aphelionz** [comment]
@pkdash I'm getting a specific error here. It's strange because the jenkins test pass on hydroshare but the error suggests that maybe they shouldnt.

This is the code I'm running:

```
from hs_restclient import HydroShare, HydroShareAuthBasic

auth = HydroShareAuthBasic(username="admin", password="default")
hs = HydroShare(auth=auth, hostname="192.168.56.101", port=8000, verify=False, use_https=False)

file_tuple = ("DESCRIPTION.rst", open("DESCRIPTION.rst"), 'text/plain')
hs.resource('dfa1b5f501484c4189879816c65ae5fe').files({ 'folder': "/", "file": file_tuple })
```

I get a 500 error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
    request = self.initialize_request(request, *args, **kwargs)
  File "/hydroshare/hs_core/views/resource_rest_api.py", line 1025, in initialize_request
    request.POST.update(old_post_data)
  File "/usr/local/lib/python2.7/site-packages/django/utils/datastructures.py", line 456, in update
    self.setlistdefault(key).extend(value_list)
  File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line 408, in setlistdefault
    self._assert_mutable()
  File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line 376, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
```

This is based on the code here: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_rest_api.py#L403-L410

So my questions are:
1. What's the actual workaround here?
2. Why would the jenkins test apps on hydroshare, but the same sort of call with hs_restclient fails?

**Comment by pkdash** [comment]
The code that raising the exception is here which is same code that you provided the link for:
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_rest_api.py#L1018'

My guess is on line 1018 the if condition is always false when Jenkins running the test. For some reason if the condition becomes true, then the call ```request.POST.update()``` will fail since POST is an immutable dict. So this is a bug in our code. 

However, the hs_restclient ```addResourceFile()``` function seems to work. See if you change the new ```files()``` to use the ```_prepareFileForUpload()``` does it resolve this error.
