### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hs_restclient#9]
Library needs to be debugged and updated to work with Python 3.

**Comment by valentinedwv** [comment]
https://jenkins.renci.org/view/RestClient/job/RestClientBuilds/

Tests fail  on assertion of basestring. What other issues should we check.
NameError: name 'basestring' is not define

======================================================================
ERROR: test_create_get_delete_resource (__main__.TestGetResourceList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_hs_restclient.py", line 113, in test_create_get_delete_resource
    newres = hs.createResource(rtype, title, resource_file=fname, keywords=keywords, abstract=abstract)
  File "/var/lib/jenkins/shiningpanda/jobs/99ea5920/virtualenvs/d41d8cd9/lib/python3.4/site-packages/hs_restclient-1.1.0-py3.4.egg/hs_restclient/__init__.py", line 481, in createResource
    close_fd = self._prepareFileForUpload(params, resource_file, resource_filename)
  File "/var/lib/jenkins/shiningpanda/jobs/99ea5920/virtualenvs/d41d8cd9/lib/python3.4/site-packages/hs_restclient-1.1.0-py3.4.egg/hs_restclient/__init__.py", line 180, in _prepareFileForUpload
    if isinstance(resource_file, basestring):
NameError: name 'basestring' is not defined

======================================================================
ERROR: test_create_get_delete_resource_file (__main__.TestGetResourceList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/99ea5920/virtualenvs/d41d8cd9/lib/python3.4/site-packages/httmock.py", line 192, in inner
    return func(*args, **kwargs)
  File "test_hs_restclient.py", line 150, in test_create_get_delete_resource_file
    resp = hs.addResourceFile(res_id, fpath)
  File "/var/lib/jenkins/shiningpanda/jobs/99ea5920/virtualenvs/d41d8cd9/lib/python3.4/site-packages/hs_restclient-1.1.0-py3.4.egg/hs_restclient/__init__.py", line 572, in addResourceFile
    close_fd = self._prepareFileForUpload(params, resource_file)
  File "/var/lib/jenkins/shiningpanda/jobs/99ea5920/virtualenvs/d41d8cd9/lib/python3.4/site-packages/hs_restclient-1.1.0-py3.4.egg/hs_restclient/__init__.py", line 180, in _prepareFileForUpload
    if isinstance(resource_file, basestring):
NameError: name 'basestring' is not defined

----------------------------------------------------------------------
